name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phonemizers:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet test tests/OpenWebtau.Phonemizers.Tests
